CREATE TABLE IF NOT EXISTS Photo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    photo_id INTEGER,
    big BOOLEAN
);
CREATE TABLE IF NOT EXISTS User (
    id INTEGER PRIMARY KEY,
    photo_id INTEGER
);
